### ISSUE TITLE
Updating reservation

### ISSUE THREAD

**Issue by evehmane** [City-of-Helsinki/huvaja#127]
Needs mockup/specs (because also the resource can change)

**Comment by YoYuUm** [comment]
+ Update reservation page
  - [ ] Create new page (/reservation/<id>/update ?)
  - [ ] Add new route

+ [ ] Create updateReservation action.

+ ReservationForm
- [ ] Adapt or create a new reservation form container so it has updateReservation
      action
- [ ] Adapt component so allows either create or update reservation.
    - Resource field should be enabled when updating reservation and include
      a button to open a resource selector modal
    - Perhaps the footer should be different for updating reservation as well

+ Resource Available / Unavailable selector Modal
  - [ ] selector 
    - Current resource
    - List of available resources.
    - List of reserved resources.
  - [ ] component

**Comment by FelixLoether** [comment]
> Calls fetchResources action on mount.

The branch Eero is working on will fetch these always in AppContainer.componentWillMount. This feature should probably do the same or otherwise we'll end up fetching the resources both on app load and when this page loads.

> Add new route (/reservation/\<id\>/update ?)

I vote for `/reservations/<id>/edit`.

> Time selector should be a dropdown when updating reservation

The time fields are text fields, not dropdowns. And the create form already includes the DateTimeRange, which renders date + start time + end time fields and should also be used in the edit form. But the create form also has the timeline, which shouldn't be included in the edit form.

> Footer should be different for updating reservation as well
so it includes the copy button and shows possible errors. Including errors
about resource/time overlaps

I don't think it's super important that it's in the footer. If it's easier to have it somewhere else (for example underneath a field), then do it that way at least at first.

**Comment by YoYuUm** [comment]
@FelixLoether 

> > Footer should be 
> > different for updating reservation as well
> > so it includes the copy button and shows possible errors. Including errors
> > about resource/time overlaps
> 
> I don't think it's super important that it's in the footer. If it's easier to have it somewhere else (for example underneath a field), then do it that way at least at first.

Do you think it could be part of the UpdateReservationPage?

**Comment by FelixLoether** [comment]
> Do you think it could be part of the UpdateReservationPage?

It'd probably be difficult to get the form validation errors from outside the form. I think the only places that have easy access to those are the form and the fields.

**Comment by evehmane** [comment]
## New structure

### Issue: Pages for creating and editing reservation
Components:
- CreateReservationPage: /reservations/create?resource=qwerty&start=...end=
  - CreateReservationFormContainer
    - ReservationForm (fetches resource for the day or there could be wrapper component to do the fetching)
- EditReservationPage (fetches reservation) /reservations/id/edit
  - EditReservationFormContainer
    - ReservationForm (fetches resource for the day or there could be wrapper component to do the fetching)
- Timeline should be shown in both cases

### Issue : ResourceSelector (See #149 and #151 when planning this)
- Update timeline when resource or day changes

### Issue: Showing errors - #166

### Issue D: Modal for showing resource information
- Modal can be opened from a button below the resource field
- There will be a mockup

### Issue: Open create or edit reservation page when needed
- User clicks time slot -> open create page with time and resource in url
- Add “Edit” button to reservation modal that opens edit page
